environment:
  R_CHECK_ARGS: --no-build-vignettes --no-manual

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_bioc sangerseqR
  - travis-tool.sh github_package ropensci/rgbif ropensci/rinat ropensci/bold ropensci/taxize ropensci/rvertnet iDigBio/ridigbio

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

notifications:
  - provider: Slack
    auth_token:
      secure: Da1t3XpyPl/xPpY98Ay83DJc6J0p8jsdu5GB3dMVBypGXGSss6D/4rzHdCmN+xNu
    channel: builds
